### ISSUE TITLE
Generated *Node.h and *Node.cpp files cause problems when service is a stream only

### ISSUE THREAD

**Issue by TE-JoakimElvander** [thejinchao/turbolink#13]
When a service is only a stream, the generated blueprint node files contains only #include statements and are otherwise empty.
This is expected due to the notice file stating that nodes for stream services are unsupported.
But the generated code causes problems because the files exist, and one of the includes is the <name>Node.generated.h which obviously don't exist as no code has been spawned in the files that could cause the generated header to be created.

**Comment by thejinchao** [comment]
Thanks, it has been fixed.
