### ISSUE TITLE
can't build project on mac m1 ue 5.2

### ISSUE THREAD

**Issue by slavaslava56ru** [thejinchao/turbolink#14]
I have error:
Undefined symbols for architecture arm64

**Comment by slavaslava56ru** [comment]
On my windows pc, all good

**Comment by slavaslava56ru** [comment]
I solved the problem. I rebuilt all the libraries and updated the dependency config so that it can be built on both intel and arm

**Comment by thejinchao** [comment]
Glad you figured it out. I don't have a mac computer with arm64 architecture, so I don't know how to compile code for multiple architectures on mac

**Comment by slavaslava56ru** [comment]
Can you please tell me how can I get a binary string to use in my code. I want to keep protobuff but not use grpc.
I thought serializeToString() would work. But as I understand it, when converting it to FSTRING, the string is not converted correctly

**Comment by slavaslava56ru** [comment]
I solved the problem. Do not convert to fstring)
