### ISSUE TITLE
Blocked at install step2 

### ISSUE THREAD

**Issue by tensmyo** [thejinchao/turbolink#23]
Hi, Thank you for your great work. 

I am blocked at the step 2
I didn't see any config contents on "project settings" window.
Did I missed anything at step 1?

> 1 . Installing the plugin
>  Download a release version from [here](https://github.com/thejinchao/turbolink/releases).
> You can also clone this repo locally through git, but you also need to download pre-built third party binaries libraries from [here](https://github.com/thejinchao/turbolink-libraries/releases), and extract it to Source/ThirdParty.
> Create a Plugins/TurboLink folder under your project folder, then copy this repo into it.

> 2. Config service endpoint

created a plugins/TurboLink folder and pull all data from https://github.com/thejinchao/turbolink/releases
I trieed : 
- restart ue5 
- put turbolink in to ue/engine/plugins/turbolink 
  - ue5 says doesn't support turbolink 4.27 
 
Appliciate that if somebody can help me fix this or help me to compile Turbolink for UE5.3.

Environment : UE 5.3 
OS: Windows 10 Pro, 64bit

**Comment by thejinchao** [comment]
edit the plugin desc file `TurboLink.uplugin`,  change the `EngineVersion` from to `5.3.0`

**Comment by thejinchao** [comment]
I have merged the ue5.3 version into the trunk and can use it directly.

**Comment by tensmyo** [comment]
@thejinchao 
Thank you for your great work. 
I have tried to rebuild it for ue5, and something goes wrong. 
Great appreciate again.

**Comment by tensmyo** [comment]
@thejinchao  
I have tried the ue5.3 version and get a message : 
> The following modules are missing or built with a differenet unreal engine.
> TurboLinkGrpc, 
> TurboLinkEditor
> Would you like to rebuild them now?

**Comment by tensmyo** [comment]
Rebuilt and everything works ! 
Thank you for your help

**Comment by andrewbdt** [comment]
How exactly did you rebuild it? I keep getting the same error:
The following modules are missing or built with a differenet unreal engine.
TurboLinkGrpc,
TurboLinkEditor
Would you like to rebuild them now?
