### ISSUE TITLE
can't achieve to built Project on Linux for Linux

### ISSUE THREAD

**Issue by 6r0m** [thejinchao/turbolink#26]
on the build stage LinuxEditor tries to link into .so library Turbolink module when cooking stage is processing. but with Errors - that third party libraries haven't Position Independent Code.

I have tried to recompile relevant gRPC, abseil and protobuf versions as shared libraries, but without luck - multiple errors with undefined symbols.

Did you try to make project builds on Linux OS?

**Comment by 6r0m** [comment]
I've managed build gRPC with some useful info from the forums, it's about libc++ version:
https://forums.unrealengine.com/t/how-to-build-static-library-for-cross-compilation-to-linux/451011
https://forums.unrealengine.com/t/compiling-libraries-in-linux/400275
https://forums.unrealengine.com/t/compile-protobuf-on-linux-for-ue4/483266/3

also I saw in the EngineThirdParty libraries scripts with BuildForLinux.

will be super cool if you include scripts to build relevant to the Turbolink libraries by the Engine analogy

**Comment by thejinchao** [comment]
sorry, I don't have the energy to take care of this project recently due to work problems, and I don't have a suitable Linux compilation environment to test it, so I'm sorry that I can't help you at the moment.

**Comment by 6r0m** [comment]
@imfr95 yes, as I wrote above https://forums.unrealengine.com/t/compiling-libraries-in-linux/400275/9?u=6r0m

**Comment by thejinchao** [comment]
The latest(v1.3.1) turbolink-libraries release support native linux build environment
