### ISSUE TITLE
Can't download the demos - link broken

### ISSUE THREAD

**Issue by rootux** [thejinchao/turbolink#27]
Trying to open full demo or demo we get a google - can't download this file due to it's violation of our terms and condition

https://drive.google.com/file/d/10qtKq2E2I7mS8M0fiFxAtuaO2Zb60-zB/view?usp=sharing

🙏🏼 
Perhaps you can upload it to another repository?

**Comment by thejinchao** [comment]
Thanks for reminding. I have uploaded the file to dropbox.
