### ISSUE TITLE
Reuse UGrpcService object

### ISSUE THREAD

**Issue by ZezhongWang** [thejinchao/turbolink#3]
现在 UGrpcService/UGrpcClient 在每次调用蓝图的节点时都会被新创建销毁，为什么不把 UGrpcService 做成和 ServiceChannel 一样全局唯一的呢？这样可以减少很多不必要的反复创建销毁。

个人认为只有 Context 是需要临时创建的。 GrpcService 不应该临时创建才对。
还有对 GrpcClient 这个类存在的目的不是很明白。 感觉 Manager -> Service -> Context 的抽象已经可以满足需求。

**Comment by thejinchao** [comment]
> 现在 UGrpcService/UGrpcClient 在每次调用蓝图的节点时都会被新创建销毁，为什么不把 UGrpcService 做成和 ServiceChannel 一样全局唯一的呢？这样可以减少很多不必要的反复创建销毁。
你说的应该是异步蓝图节点吧，这种调用方式适用于那些在项目中只调用一次的接口，比如登录，获取配置文件这样的接口。对于需要长时间通讯的接口，可以在蓝图中创建Service和Client对象，再调用对应的rpc接口。可以参考下我给的那个[Demo工程](https://drive.google.com/file/d/1mb9lZB_ai485sbLtqrw-bk5NtlWK8fgh/view?usp=share_link)中TimeService相关的调用方式。

> 还有对 GrpcClient 这个类存在的目的不是很明白。 感觉 Manager -> Service -> Context 的抽象已经可以满足需求。
Client的存在还是有必要的，Client的目的是管理不同的rpc回调入口。比如在游戏服务器中，有一个提供角色数据的rpc接口，那么在客户端，不同的角色Actor（主角、NPC、队友、敌人）在调用这个接口时的回调入口也是不一样的，这样在这些Actor中可以各自创建不同的Client对象来管理回调函数。

**Comment by ZezhongWang** [comment]
关于 Client 的部分我理解了。但是头一个 Service 的问题还不是很理解，还是认为 Service 可以做成全局唯一的。
至少异步蓝图节点预计会在我们项目中得到充分使用。就比如说提供角色数据的接口 AvatarService，什么情况下需要创建两个 AvatarService 实例呢？如你所说既然 Client 已经满足了这个需求，那么Service 就不需要存在多个了。

**Comment by thejinchao** [comment]
异步蓝图节点比较特殊，其实我是不鼓励使用这种节点的，虽然看起来方便，但是限制很多，比如没法处理stream类型的接口，没法处理断线重连等异常情况，所以我的本意是异步蓝图节点只用来做一些一次性的接口调用，所以没有为它增加service管理器这种设计

**Comment by thejinchao** [comment]
另外UGrpcService本身并不消耗什么资源，它只是对底层grpc::Channel的封装，而Channel的管理是以Endpoint区分的，所以虽然创建了多个Service对象，但底层的Channel其实是同一个

**Comment by ZezhongWang** [comment]
但是 UGrpcService 每次会创建新的 Stub。这个是与 grpc 的 best practice 相违背的

**Comment by thejinchao** [comment]
> 但是 UGrpcService 每次会创建新的 Stub。这个是与 grpc 的 best practice 相违背的

你说的有道理，Channel是TCP协议层的连接对象，Stub是应用层对应的grpc链接对象，按说每个gRPC Service在客户端中都可以只创建一个Stub的，不过因为Stub的创建代码属于Generated Code，当时没有找到比较“优雅”的实现方式，而且Stub本身所占用的资源很少，所以就把他放在Service里了，后来没有再考虑这个事情，我后面可以考虑下实现这个管理

**Comment by ZezhongWang** [comment]
我的意思是可不可以 Service 也做成跟 channel 一样，同类型 Service 的对象是全局唯一的。例如更改一下 MakeService 的实现，如果已有该 Service 对象则返回旧的对象：
```
UGrpcService* UTurboLinkGrpcManager::MakeService(const FString& ServiceName)
{
	UClass** serviceClass = ServiceClassMap.Find(ServiceName);
	if (serviceClass == nullptr)
	{
		return nullptr;
	}

	auto serviceIteractor = ServiceMap.find(ServiceName);
	if (serviceIteractor != ServiceMap.end())
	{
		return serviceIteractor->second;
	}

	UGrpcService* service = NewObject<UGrpcService>(this, *serviceClass);
	service->TurboLinkManager = this;
	ServiceMap.insert(std::make_pair(ServiceName, service));
	return service;
}
```

**Comment by thejinchao** [comment]
看起来这样解决是可以的，我考虑下，谢谢提醒

**Comment by thejinchao** [comment]
提交了一个新的版本，把这个功能加上了，你可以试下
