### ISSUE TITLE
CLANG BUG FIX: expected a qualified name after 'typename'

### ISSUE THREAD

**Issue by savasozer** [thejinchao/turbolink#33]
While building the plugin in v22_clang-16.0.6-centos it gives the following error

>Plugins\Turbolink\Source\TurboLinkGrpc\Private\TurboLinkGrpcContext.h(201,12): error: expected a qualified name after 'typename'
> typename FSendCompleteCallbackFunc SendCompleteCallbackFunc)

To fix:
![image](https://github.com/thejinchao/turbolink/assets/12625556/b0d4a1e7-9195-4596-b7f4-cf95f70caecc)

**Comment by thejinchao** [comment]
thank you very much, fixed it.
