### ISSUE TITLE
Is it supported for use with PixelStreaming plugin?

### ISSUE THREAD

**Issue by ChEnYoNgB** [thejinchao/turbolink#34]
As far as I know, some functions in abseil will be redefined in webrtc.lib in PixelStreaming resulting in link errors. （This error can be replicated by adding the WebRTC module to UE）Does your plugin have this problem?

**Comment by 6r0m** [comment]
I'm using it with Pixel Streaming Plugin without any problem

**Comment by thejinchao** [comment]
Although I am not too sure, after preliminary testing, there should be no problem
