### ISSUE TITLE
Example client crashes when stop the game client.

### ISSUE THREAD

**Issue by ZezhongWang** [thejinchao/turbolink#4]
It seems that the turbolink has issue with deleting resource. It can easily crash when stop the game.

Reproduce crash:
- Open the client in editor
- Start the game, using blueprint widget
- click connect, create client, tiktok, watch randomly
- Stop the game. crash sometimes happen.

Environment: Win 11, Unreal 5.1
local client: example client
remote Server: grpc.thecodeway.com:5050

```
LoginId:0efd37ca4c6c7474efb2c99e5bb384e9
EpicAccountId:11a9f14e5c654a5989f30cc488bee675

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x000007778a89b640

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_TurboLinkDemo!UTurboLinkDemoInstance::`vector deleting destructor'()
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Comment by thejinchao** [comment]
我平时的确主要是使用UE4.27，UE5只是试了下能跑起来，我抽时间仔细调试下，多谢提醒！

**Comment by thejinchao** [comment]
发现问题了，Demo工程里在`UTurboLinkDemoInstance::Shutdown`这个函数里忘调用`Super::Shutdown`了，导致停止的时候某些底层系模块没有被正确析构，在UE4上没有什么表现，但是在UE5里抛异常了。
你可以自己把这行代码加上，或者重新下载这个[Demo工程](https://drive.google.com/file/d/1mb9lZB_ai485sbLtqrw-bk5NtlWK8fgh/view?usp=share_link)，我已经更新版本了，再次感谢提醒。

**Comment by ZezhongWang** [comment]
Problem fixed. Thx.
