### ISSUE TITLE
how to filter abseil libraries not been used？

### ISSUE THREAD

**Issue by ZezhongWang** [thejinchao/turbolink#5]
我看到你的project中把不被使用的 abseil libraries 过滤掉了，请问这是如何确定的呢？
我现在在做 grpc 1.50.0 的适配。 之后可以把我的分支提交到你的 repo。

https://github.com/ZezhongWang/turbolink-libraries/tree/grpc_v1.50.0

![image](https://user-images.githubusercontent.com/28833999/213442992-117f32ab-8e0d-42aa-a9f0-ee01b4628d7a.png)

**Comment by thejinchao** [comment]
其实很容易，把gRPC提供的helloworld工程用cmake生成出来，然后在vs里看下都link了哪些库就行了
![image](https://user-images.githubusercontent.com/1171276/213691368-7f68bd65-6456-4878-bb89-62041e18b921.png)

**Comment by ZezhongWang** [comment]
原来如此，机智机智。
