### ISSUE TITLE
No Support For Transcoding

### ISSUE THREAD

**Issue by WilSimpson** [thejinchao/turbolink#6]
If there is no support for `oneof` then any services using [transcoding](https://cloud.google.com/endpoints/docs/grpc/transcoding) won't be supported. I believe this may be an issue for many developers. What's the main issue with supporting this field?

**Comment by thejinchao** [comment]
Technically, it is actually achievable, mainly because implementing functions like `has_foo` and `clean_foo` in the blueprint will make the generated code more complicated. But I don't quite understand why `oneof` is related to `trasncoding`, can you explain? thanks.

**Comment by thejinchao** [comment]
Understood, thank you for sharing this information！
I will consider adding these supports in future versions, but it does take some time.

**Comment by thejinchao** [comment]
Hi, You can try the new version. For the message file that contains the definition of transcoding, the correct code can be generated now.
But there is a problem that I don't quite understand. If the server uses the REST protocol, then the client can directly use the HTTP protocol and JSON-type data, so you shouldn't need this plug-in. I don't know what I understand. is it right or not?

**Comment by WilSimpson** [comment]
> Hi, You can try the new version. For the message file that contains the definition of transcoding, the correct code can be generated now. But there is a problem that I don't quite understand. If the server uses the REST protocol, then the client can directly use the HTTP protocol and JSON-type data, so you shouldn't need this plug-in. I don't know what I understand. is it right or not?

Great news! I haven't used this plugin in awhile, but when I was working with it I was also able to get it work by modifying your generation script. The use for transcoding is for support outside of gRPC. This plugin won't use this functionality, but it is used other places in the architecture. 

I'm not sure if it has since been fixed, but there were some large issues with the protobuf code generator that also makes this plugin useful for me as of now. If I have time in the future I'd be happy to help but I don't at the moment. When I have time I can go into more detail and create a issue on the generator if that is helpful for you.
1. When using packages with periods (eg- com.website), then the generated code incorrectly uses periods in variable or type names. Sorry I don't remember which it was.
2. When generating the protobuf messages, it goes through the file linearly (top to bottom). If there are any dependencies between messages, then the generator does not change the order in which they are declared possibly causing issues in C++ if they aren't in a valid C++ order. 
Example that would cause a problem for C++:
```
message MessageA {
  MessageB data = 1;
}

message MessageB {
  string id = 1;
}
```

**Comment by thejinchao** [comment]
Thank you for reply.  The good news is that I have solved the two problems you mentioned in the new version. 
>When using packages with periods (eg- com.website), then the generated code incorrectly uses periods in variable or type names. Sorry I don't remember which it was.
In the new version, I use the camel-case format of the package name in the UE. For example, there is a protocol file named `hello.proto`, and the name of the package is `example.com`. Then the generated UE file file structure is
```
-SExampleCom
 |--Private
 | |--HelloClient.cpp
 | |--HelloMessage.cpp
 | |-- ...
 |
 |--Public
   |--HelloClient.h
   |--HelloMessage.h
   |--HelloNode.h
   |--HelloService.h
   |-- ...
```
>When generating the protobuf messages, it goes through the file linearly (top to bottom). If there are any dependencies between messages, then the generator does not change the order in which they are declared possibly causing issues in C++ if they aren't in a valid C++ order.
I do not solve this problem by adjusting the message order, because in some cases, this problem cannot be completely solved by the adjustment order. For example, the following two protocols
```proto
message MessageA {
  MessageB msg_b = 1;
}
message MessageB {
  MessageA msg_a = 1;
}
```
My solution is to add data types of `TSharedPtr` types to `USTRUCT`,  and then use (native make and native break)[https://docs.unrealengine.com/5.1/en-US/metadata-specifiers-in-unreal-engine/#structmetadataspecifiers] functions to achieve reflection，The code generated now is as follows:
```cpp
USTRUCT(BlueprintType, meta = (DisplayName="User.MessageA",
    HasNativeMake = "TurboLinkGrpc.GrpcUserMessageAHelperLibrary.MakeMessageA",
    HasNativeBreak = "TurboLinkGrpc.GrpcUserMessageAHelperLibrary.BreakMessageA"))
struct FGrpcUserMessageA : public FGrpcMessage
{
    GENERATED_BODY()
    TSharedPtr<FGrpcUserMessageB> MsgB;
};

USTRUCT(BlueprintType, meta = (DisplayName="User.MessageB"))
struct FGrpcUserMessageB : public FGrpcMessage
{
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    FGrpcUserMessageA MsgA;
};

UCLASS()
class UGrpcUserMessageAHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|User", meta=(BlueprintThreadSafe))
    static FGrpcUserMessageA MakeMessageA(FGrpcUserMessageB MsgB);

    UFUNCTION(BlueprintPure, Category = "TurboLink|User", meta=(BlueprintThreadSafe))
    static void BreakMessageA(const FGrpcUserMessageA& MessageA, FGrpcUserMessageB& MsgB);
};
```
```cpp
FGrpcUserMessageA UGrpcUserMessageAHelperLibrary::MakeMessageA(FGrpcUserMessageB MsgB)
{
    FGrpcUserMessageA MessageA;
    MessageA.MsgB = MakeShareable(new FGrpcUserMessageB(MsgB));
    return MessageA;
}
void UGrpcUserMessageAHelperLibrary::BreakMessageA(const FGrpcUserMessageA& MessageA, FGrpcUserMessageB& MsgB)
{
    MsgB = *(MessageA.MsgB.Get());
}
```

**Comment by WilSimpson** [comment]
Nice solution, especially since it looks like it only uses reflection if needed! I'll give the plugin another go when I have time. I think these were my only issues stopping me from adopting this plugin

**Comment by WilSimpson** [comment]
Works well, thanks for the update!
